
spring:
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
    open-in-view: false
  main:
    banner-mode: 'off'

server:
  servlet:
    context-path: /capi-core

management:
  endpoints:
    web:
      base-path: /
  server:
    port: 8181
    servlet:
      context-path: /capi-core
